# Generated by Django 5.0.3 on 2024-03-29 22:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dateBilling', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dateDelivery', models.DateTimeField()),
                ('liter', models.IntegerField(default=1)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateTimeField()),
                ('ear_tag', models.IntegerField(default=1)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('type', models.CharField(choices=[('C', 'Cabri'), ('CH', 'Chevrette'), ('CHV', 'Chèvre'), ('B', 'Bouc')], max_length=3)),
                ('rebouclage_quantity', models.IntegerField(default=0)),
                ('chevre_quantity', models.IntegerField(default=0)),
                ('tiptag_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Cheese', 'Fromage'), ('Laine', 'Laine'), ('Savon', 'Savon'), ('Vannerie', 'Vannerie'), ('Peau', 'Peau de chèvre'), ('Autre', 'Autre')], default='Cheese', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dateSupplier', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_actions', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.delivery')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.modelaction')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.customerbilling')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.modelaction')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.modelaction')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.production')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBillingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.modelaction')),
                ('supplier_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.supplierbilling')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Commercial')], default='ADMIN', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='gestion_user_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='modelaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_actions_gestion', to='gestion.user'),
        ),
    ]
