# Generated by Django 5.0.3 on 2024-03-29 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='cheese', to='recipies.ingredient')),
                ('ferment_name', models.CharField(max_length=200)),
                ('ferment_quantity', models.FloatField()),
                ('ferment_mesure_unit', models.CharField(max_length=200)),
                ('cooking_time', models.IntegerField()),
                ('cooking_temperature', models.IntegerField()),
                ('refining_time', models.IntegerField()),
                ('refining_temperature', models.IntegerField()),
                ('pressing', models.BooleanField(default=False)),
                ('pressing_time', models.IntegerField()),
                ('conservation_mode', models.CharField(choices=[('Naturel', 'Naturel'), ('Sous-vide', 'Sous-vide'), ('cire', 'cire'), ('autre', 'autre')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoatSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('mesure_unit', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Soap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='soap', to='recipies.ingredient')),
                ('drying_time', models.IntegerField()),
                ('dyeing', models.BooleanField(default=False)),
                ('dyeing_color', models.CharField(max_length=200)),
                ('dyeing_preparation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Whool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='whool', to='recipies.ingredient')),
                ('fabrication_type', models.CharField(choices=[('tissage', 'tissage'), ('feutrage', 'feutrage'), ('filage', 'filage'), ('autre', 'autre')], max_length=200)),
                ('dyeing', models.BooleanField(default=False)),
                ('dyeing_color', models.CharField(max_length=200)),
                ('dyeing_preparation', models.TextField()),
                ('drying_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_actions_recipies', to='gestion.user')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.ingredient')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
            ],
        ),
        migrations.CreateModel(
            name='GoatSkinAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.goatskin')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
            ],
        ),
        migrations.CreateModel(
            name='CheeseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.cheese')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
            ],
        ),
        migrations.CreateModel(
            name='BasketryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.basketry')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
            ],
        ),
        migrations.CreateModel(
            name='OtherAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.other')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipies.recipes'),
        ),
        migrations.CreateModel(
            name='RecipesAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='SoapAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
                ('soap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.soap')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='step_attachments/')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipies.recipes')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.step')),
            ],
        ),
        migrations.CreateModel(
            name='WhoolAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.modelaction')),
                ('whool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.whool')),
            ],
        ),
    ]
